name = "dubbi"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./dist", binding = "ASSETS", html_handling = "auto-trailing-slash" }

[observability.logs]
enabled = true

[[r2_buckets]]
binding = "CATS"
bucket_name = "sbupi-cats"

[vars]
NODE_ENV = "production"

[[routes]]
pattern = "v4.jbazann.dev"
custom_domain = true